# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/samNbdevTemplate2',
                'doc_host': 'https://nic.github.io',
                'git_url': 'https://github.com/nic/samNbdevTemplate2',
                'lib_path': 'samNbdevTemplate2'},
  'syms': {'samNbdevTemplate2.core': {'samNbdevTemplate2.core.foo': ('core.html#foo', 'samNbdevTemplate2/core.py')}}}